spring.application.name=badger-events
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/badger_events}
spring.datasource.username=${DB_USERNAME:badger_app}
spring.datasource.password=${DB_PASSWORD:badger_local_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
