CREATE TABLE import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    created_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,

    CONSTRAINT chk_import_runs_status CHECK (
        status IN (
            'RUNNING',
            'SUCCESS',
            'PARTIAL_FAILURE',
            'FAILED'
        )
    ),

    CONSTRAINT chk_import_runs_counts_non_negative CHECK (
        created_count >= 0
        AND updated_count >= 0
        AND skipped_count >= 0
        AND failed_count >= 0
    )
);

CREATE TABLE import_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_run_id BIGINT NOT NULL,
    external_id VARCHAR(255),
    failure_type VARCHAR(30) NOT NULL,
    failure_message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_import_failures_import_run
        FOREIGN KEY (import_run_id)
        REFERENCES import_runs (id),

    CONSTRAINT chk_import_failures_type CHECK (
        failure_type IN (
            'MAPPING',
            'VALIDATION',
            'PERSISTENCE'
        )
    )
);

CREATE INDEX idx_import_runs_started_at
    ON import_runs (started_at DESC);

CREATE INDEX idx_import_failures_import_run_id
    ON import_failures (import_run_id);