CREATE TABLE event_interests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_event_interests_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_event_interests_event
        FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT uk_event_interests_user_event
        UNIQUE (user_id, event_id)
);

CREATE INDEX idx_event_interests_event_id
    ON event_interests (event_id);