CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_messages_event
        FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_messages_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_messages_content
        CHECK (CHAR_LENGTH(TRIM(content)) BETWEEN 1 AND 1000)
);

CREATE INDEX idx_messages_event_created_id
    ON messages (event_id, created_at, id);