CREATE TABLE chat_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_chat_memberships_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_chat_memberships_event
        FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT uk_chat_memberships_user_event
        UNIQUE (user_id, event_id)
);

CREATE INDEX idx_chat_memberships_event_id
    ON chat_memberships (event_id);

-- 이 기능을 만들기 전에 메시지를 작성한 사용자는
-- 이미 해당 채팅에 참여한 것으로 처리한다.
INSERT INTO chat_memberships (user_id, event_id, joined_at)
SELECT user_id, event_id, MIN(created_at)
FROM messages
GROUP BY user_id, event_id;